spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j2ee_demow12
    username: root
    password: 7400
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect  # Explicit MySQL 8 dialect
      format_sql: true  # Format SQL for better readability
    show-sql: true  # Log SQL statements